In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import time

In [2]:
X = np.array([[1.2, 1.5, 1.8],[1.3, 1.4, 1.9],[1.1, 1.6, 1.7]])
Y = np.array([5, 10, 9]).T

#### 使用循环的方式计算每天的采购总金额 
#### 得到结果为[37.2, 37.6, 36.8]，分别表示7/28、7/29、7/30这三天采购总额

In [3]:
balance = []
for bill in X:
    money = 0
    count = 0
    for item in bill:
        money += item*Y[count]
        count+=1
    balance.append(round(money,2))

print("Bills for 7/28、7/29、7/30: " + str(balance)  )


Bills for 7/28、7/29、7/30: [37.2, 37.6, 36.8]


#### 使用矩阵点乘来计算每天的采购总金额（使用np.dot来实现矩阵相乘）

In [4]:
np.dot(X,Y.T)

array([37.2, 37.6, 36.8])

#### 测试性能

In [5]:
%timeit np.dot(X,Y.T)

1.57 µs ± 4.15 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [6]:
%%timeit
balance = []
for bill in X:
    money = 0
    count = 0
    for item in bill:
        money += item*Y[count]
        count+=1
    balance.append(round(money,2))


22.3 µs ± 593 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


## Project 2

In [7]:
np.random.seed(1)
X = np.random.randint(1, 10, size=30)
X

array([6, 9, 6, 1, 1, 2, 8, 7, 3, 5, 6, 3, 5, 3, 5, 8, 8, 2, 8, 1, 7, 8,
       7, 2, 1, 2, 9, 9, 4, 9])

#### 请将X处理为一个3列的矩阵

In [8]:
X.reshape((10,3))

array([[6, 9, 6],
       [1, 1, 2],
       [8, 7, 3],
       [5, 6, 3],
       [5, 3, 5],
       [8, 8, 2],
       [8, 1, 7],
       [8, 7, 2],
       [1, 2, 9],
       [9, 4, 9]])

#### 将第三列中，小于等于3的修改为0、大于3且小于等于6的修改为1、
#### 大于6的修改为2，结果如

In [9]:
arr = X.reshape((10,3))
col3 = arr[:,-1]
col3

array([6, 2, 3, 3, 5, 2, 7, 2, 9, 9])

In [10]:
for i in range(len(col3)):
    if col3[i]<=3:
        col3[i] = 0
    elif col3[i]> 6 :
        col3[i] = 2
    else :
        col3[i] = 1
col3

array([1, 0, 0, 0, 1, 0, 2, 0, 2, 2])

In [11]:
X3 = np.concatenate([arr[:,:2], col3.reshape((10,1))], axis = 1)
X3

array([[6, 9, 1],
       [1, 1, 0],
       [8, 7, 0],
       [5, 6, 0],
       [5, 3, 1],
       [8, 8, 0],
       [8, 1, 2],
       [8, 7, 0],
       [1, 2, 2],
       [9, 4, 2]])

#### X_train 存放样本特征(红色部份), y_train 存放分类标记(绿色部份)

In [12]:
X_train = X3[:,:2]
X_train

array([[6, 9],
       [1, 1],
       [8, 7],
       [5, 6],
       [5, 3],
       [8, 8],
       [8, 1],
       [8, 7],
       [1, 2],
       [9, 4]])

In [13]:
Y_train  =X3[:,-1].reshape((10,1))
Y_train

array([[1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [2],
       [0],
       [2],
       [2]])

#### 请用numpy 的比较运算，通过 y_train 中的数据，分离出 X_train 中的3 个分类，如下图

In [14]:
result = []
for i in range(0,3):
    print("***********分类为 "+str(i)+ " 的样本： ")
    result = np.where(Y_train ==i)
    print(X_train[result[0]])



***********分类为 0 的样本： 
[[1 1]
 [8 7]
 [5 6]
 [8 8]
 [8 7]]
***********分类为 1 的样本： 
[[6 9]
 [5 3]]
***********分类为 2 的样本： 
[[8 1]
 [1 2]
 [9 4]]
